version: '2'
services:
  hadoop-master:
    image: segence/hadoop:0.2.2
    container_name: hadoop-master
    hostname: hadoop-master
    ports: # HOST:CONTAINER
      - "2222:2222"
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8033:8033"
      - "8088:8088"
      - "9000:9000"
      - "50010:50010"
      - "50070:50070"
      - "50090:50090"
    environment:
      - HADOOP_NAMENODE_HOST=hadoop-master
    volumes:
      - ./data-master:/data
      - ./slaves-config:/config:ro
      - ./deployments:/deployments:ro
    tty: true
    networks:
      hadoop:
        aliases:
         - hadoop-master
  hadoop-slave1:
    image: segence/hadoop:0.2.2
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    environment:
      - HADOOP_NAMENODE_HOST=hadoop-master
    volumes:
      - ./data-slave1:/data
      - ./slaves-config:/config:ro
    tty: true
    networks:
      hadoop:
        aliases:
         - hadoop-slave1
networks:
  hadoop:
    driver: bridge
