version: '2'
services:
  hadoop-master:
    image: segence/hadoop:0.2.1
    container_name: hadoop-master
    ports: # HOST:CONTAINER
      - "2222:2222"
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8033:8033"
      - "8042:8042"
      - "8080:8080"
      - "8088:8088"
      - "9000:9000"
      - "50070:50070"
      - "50090:50090"
    volumes:
      - ./data-master:/data
      - ./slaves-config:/config:ro
      - ./deployments:/deployments:ro
    tty: true
